name: P-UNIT-PROJECT-CI-MICROSERVICE-NODE

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths-ignore:
      - '**/README.md'
      - '**/.gitignore'
      - '**/.dockerignore'
      - '**/.eslintrc.json'

jobs:
  tests:
    name: Tests
    uses: gitdsoares/templates/.github/workflows/tests.yml@main
    with:
      APP_NAME: ${{ vars.APP_NAME }}

  compliance:
    name: Compliance
    uses: gitdsoares/templates/.github/workflows/compliance.yml@main
    permissions: write-all
    with:
      APP_NAME: ${{ vars.APP_NAME }}
    secrets:
      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      DOCKER_PAT: ${{ secrets.DOCKER_PAT }}

  build:
    name: Build
    uses: gitdsoares/templates/.github/workflows/build.yml@main
    needs: compliance
    with:
      APP_NAME: ${{ vars.APP_NAME }}
    secrets:
      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
      GIT_PAT: ${{ secrets.GIT_PAT }}